feat: navbar refactor, buttons, auth modals
qri-io/frontend pull request #101
Opened 2021-02-12 21:05 UTC by chriswhong

Refactors `NavBar` to be a layout component with `brand`, `left`, and `right` content areas.  This allows us to more easily compose NavBars depending on the current route and login state.

Refactors `PageLayout` to be a layout component with `top` and `main` content areas (so NavBar can be composed separately and passed in as `top` content.

Adds `Button` component to standardize buttons across the app.  Buttons can 
be implemented with `type` and `size` props.

Adds LogIn and SignUp modals as custom modal layouts that do not use the `ModalLayout`.  These include links to each other, links to TOS and Privacy, and a rudimentary `TextInput` component, but are not wired up to actions and do not yet have error handling UI.

<img width="1042" alt="Home___Qri_Cloud_and_ExternalLink_tsx_—___qri_qrimatic" src="https://user-images.githubusercontent.com/1833820/107822048-78b47800-6d4b-11eb-9d9e-098325182281.png">

2021-02-12 21:31 UTC, b5 requested changes

2021-02-12 21:31 UTC, b5 commented on frontend/src/chrome/Button.tsx
> +export type ButtonType = 'primary' | 'light' | 'danger' | 'dark'
Lovely string union! I personally prefer them spread across lines when defined:

```ts
export type ButtonType =
  | 'primary'
  | 'light'
  // ...
```

2021-02-12 21:31 UTC, b5 commented on frontend/src/chrome/Button.tsx
> +const Button: React.FC<ButtonProps> = ({ type='primary', size='md', className, onClick, children }) => {
split prop restructuring onto new lines as well

2021-02-12 21:31 UTC, b5 commented on frontend/src/chrome/ExternalLink.tsx
> +export const ExternalLink: React.FunctionComponent<ExternalLinkProps> = ({ id, to, children, className, tooltip }) =>
spread prop destructing across multiple lines. I'm v into the `to` rename

2021-02-12 21:31 UTC, b5 commented on frontend/src/features/app/PageLayout.tsx
>  )
This is an over-abstraction. This components-as-props pattern turns the `PageLayout` component into a black box that requires the reader open it up to understand the DOM structure. 

If a component doesn't want a `NavBar` in the header it  shouldn't use the `PageLayout` component. Make a second layout component instead.

With Very limited exception we should alway pass children to components using React's built-in `<Component><Child></Component>` / `children` prop.

2021-02-12 21:31 UTC, b5 commented on frontend/src/features/activityFeed/CollectionActivityFeed.tsx
>  }
I think this code proves the point about the changes to the `PageLayout` API. We might want to consider renaming `PageLayout` to something more specific.

2021-02-12 21:31 UTC, b5 commented on frontend/src/features/navbar/UserMenu.tsx
> +import React from 'react'
move this to a new `sessionUser` feature folder (`/src/features/sessionUser`), rename to `sessionUserMenu`

2021-02-12 21:31 UTC, b5 commented on frontend/src/features/app/modal/SignUpModal.tsx
> +          />
This component is a great setup for thinking about validation next sprint 😄

2021-02-12 21:31 UTC, b5 commented on frontend/src/features/app/modal/SignUpModal.tsx
> +          By continuing, you agree to Qri's <ExternalLink to='https://qri.io/legal/tos'>Terms of Service</ExternalLink> & <ExternalLink to='https://qri.io/legal/privacy-policy'>Privacy Policy</Extern
Loving this `ExternalLink`

2021-02-12 21:31 UTC, b5 commented on frontend/src/features/navbar/NavBar.tsx
>  }
This is another example of over-abstraction. The better way to handle this is with different types of `NavBar` components. Passing react components as Props. Seems to me what we're really after here are multiple variations of "`PageLayout`" (`DatasetPageLayout`/`NavPageLayout`/`FullscreenPageLayout`) that may make use of different Navbar components.

2021-02-16 17:47 UTC, chriswhong commented on frontend/src/features/navbar/NavBar.tsx
>  }
Replaced NavBar with two variants one for Authenticated Users and one for Anonymous Users

2021-02-16 17:48 UTC, chriswhong commented on frontend/src/features/app/PageLayout.tsx
>  )
Replaced PageLayout with two variants, one where there is a user and one for anonymous users.

2021-02-16 17:48 UTC, chriswhong commented on frontend/src/features/activityFeed/CollectionActivityFeed.tsx
>  }
Now uses `UserPageLayout`

2021-02-16 20:36 UTC, b5 approved these changes
Okay, so I think this set of changes introduces a new bunch of concerns with regard to transitions in session states: when a user logs in / session is acquired, we'll need to reload the page under this paradigm.

Generally I think this `Layout` approach causes more problems than it solves, and I think the better solution is to move away from it, and toward "thickening" components like navbar into containers that can select from the state tree.

All that said, we can totally land this sort of refactor atop this existing PR, which adds modals we very much need. So I vote we merge this & iterate atop it

2021-02-16 20:37 UTC, merged