fix: added logic to hide the output and status of each cell/outline on edit while remaining the events list intact
qri-io/frontend pull request #371
Opened 2021-10-06 07:07 UTC by boandriy

added logic to hide the output and status of each cell/outline on edit while remaining the events list intact
fixed the output clear action to hide the output of single cell

fixes #313

2021-10-06 14:38 UTC, ramfox requested changes
everything looks good, but I think the logic for the cell outlines is off, based on the comment's chris left on the issue

2021-10-06 14:38 UTC, ramfox commented on src/features/workflow/CodeEditor.tsx
> +    }else{
Based on chris' answer on the issue I think the logic here isn't right (here is the comment: https://github.com/qri-io/frontend/issues/313#issuecomment-929369275)

When any cell as been edited, the *sidebar* and *all of the cells* should not have a "success" border any more & show a symbol that indicates that it is not in a valid state. In this comment, he mentions using the gray circle with the line as the symbol: https://github.com/qri-io/frontend/issues/313#issuecomment-929380395

2021-10-11 15:04 UTC, chriswhong commented
![image](https://user-images.githubusercontent.com/1833820/136812556-cfe6e300-32e0-4a43-88bc-eafe15674d59.png)

When testing this locally, I see this green outline appearing on hover.  If this is the "active" state of the cell, it should not be related to hover and should just appear this way when the user has clicked it it and is ready to edit, regardless of whether they have made changes.

 On this note, we need a way for the current cell to stay active AND to show that its last run was successful.

On deepnote, they use the icon to indicate success, but there is no outline color for success/failure.  The outline is only used for the "active" cell that the user is interacting with.

When the user edits the cell, the results stay, but the icon disappears.

2021-10-12 13:44 UTC, b5 commented
where are we at with this? need re-review? @chriswhong have you confirmed it works as expected?

2021-10-12 13:58 UTC, chriswhong commented
Yes, I pushed changes that are working as expected, just need the ok on code quality/maintainability

2021-10-12 15:16 UTC, b5 commented on src/features/workflow/state/workflowState.ts
> +  areCellsEdited: boolean[]
don't use `are` in a field name: `areCellsEdited` -> `editedCells`

2021-10-12 15:16 UTC, b5 commented on src/features/workflow/state/workflowState.ts
> +  areCellsOutputCleared: boolean[]
`areCellsOutpuCleared` -> `clearedOutputCells`

2021-10-12 15:16 UTC, b5 commented on src/features/workflow/WorkflowCell.tsx
> +import { useSelector } from "react-redux";
keep npm / external package imports grouped at the top

2021-10-13 17:50 UTC, merged