feat: persis output on new runs
qri-io/frontend pull request #436
Opened 2021-10-18 11:31 UTC by boandriy

When you do consecutive dry-runs, the output of the cells will persist until the new output is calculated. 

closes #394

2021-10-19 13:57 UTC, chriswhong approved these changes
All good on functionality!

2021-10-19 14:17 UTC, ramfox requested changes
Just a bit of a refactor of the `Output` component.

Let's change the `data` param so that it is required.

Then in `src/features/workflow/output/Output.tsx`, we can remove the check to see if `data` exists before we apply the `map`.

In `WorkflowCell`, this means that we should have the `output` variable only be `EventLogLine[]`, and not give it an option for `undefined`.

2021-10-19 14:17 UTC, ramfox commented on src/features/workflow/WorkflowCell.tsx
> +  const [output, setOutput] = useState<EventLogLine[] | undefined>()
`const [output, setOutput] = useState<EventLogLine[]>(run?.output || [])`

2021-10-19 14:17 UTC, ramfox commented on src/features/workflow/WorkflowCell.tsx
> +  }, [ run, output ])
```js
  useEffect(() => {
    if (run?.status === "succeeded" && run.output) {
      setOutput(run.output)
    }
  }, [ run, output ])
```

2021-10-19 14:17 UTC, ramfox commented on src/features/workflow/WorkflowCell.tsx
> +              {(collapseState === 'all' || collapseState === 'only-output') && (output || run?.status === 'running') &&
```js
              {(collapseState === 'all' || collapseState === 'only-output') && (output.length > 0 || run?.status === 'running') &&
```

2021-10-19 14:17 UTC, ramfox commented on src/features/workflow/output/Output.tsx
> +        {status === 'running' && !data && <p className='text-qrinavy-700 text-sm'>Running...</p>}
```suggestion
        {status === 'running' && !data.length && <p className='text-qrinavy-700 text-sm'>Running...</p>}
```

2021-10-20 12:58 UTC, ramfox approved these changes
LGTM

2021-10-20 14:52 UTC, boandriy commented on src/features/workflow/WorkflowCell.tsx
> +  useEffect(() => {
@ramfox , had to do the following changes, because of the following:
1. the output for failed runs was not returning.
2. When the second if logic was removed - the output didn't clear in case run didn't return output

2021-10-20 14:57 UTC, ramfox approved these changes
LGTM!

2021-10-20 15:07 UTC, merged