refactor: implemented new user profile page design
qri-io/frontend pull request #440
Opened 2021-10-19 12:12 UTC by boandriy

implemented new user profile page design

closes #379

2021-10-19 13:54 UTC, chriswhong requested changes
Looks like we still need to remove the "following" tab and add the user's avatar image in the header.

2021-10-20 16:38 UTC, chriswhong approved these changes
Pushed some styling tweaks to get things closer to the mockups.  LGTM unless there are changes requested by engineering.

2021-10-21 13:49 UTC, ramfox approved these changes
LGTM! Just one question about some commented out code and then it's good to merge!

2021-10-21 13:49 UTC, ramfox commented on src/features/userProfile/UserProfile.tsx
> +    // }
Can you write in the TODO when it should be commented out, or remove the commented code

2021-10-22 08:44 UTC, merged