feat: adding history loading state
qri-io/frontend pull request #445
Opened 2021-10-20 10:48 UTC by boandriy

adding history loading state

2021-10-20 15:44 UTC, chriswhong requested changes
- The loading content for `CommitSummaryHeader` isn't the same height as the content, so there is a shift that happens when it appears and disappears.  Let's make sure this element has a constant height
- The tab for "Data" is wider than the other tabs by design, but during the loading state, it's the same width.  Let's make sure the Data tab is always the same width and is wider than the others.
- The body still displays "There's nothing here yet" during part of the loading... When I tested it I saw the new table with animated loading rectangles in it, but this went away, then it shows "There's nothing here yet", then the body renders.  Let's make sure the loading state table shows continuously until the body is in place.

2021-10-21 08:44 UTC, boandriy commented
Hey @chriswhong , There is still a content shift, as the header is missing on the loading state. Should I add similar content loader?

2021-10-22 12:56 UTC, chriswhong requested changes
Still seeing a very slight shift in content when switching between versions in history.  Also, the heading Version Info can stay as it doesn't change, only the content below it changes.

Can we resize/reformat the SVG so that it matches the height of the content it is replacing and prevents the shift completely?

2021-10-22 15:42 UTC, chriswhong commented
A few more changes:
- The active tab shouldn't be changing either.  I am seeing the data tab as white, then choosing another version, and it flashes gray and then white again.  Let's make sure this flash doesn't occur, the active tab should stay active through the loading state.
- I see "showing all 0 rows" for a moment which is awkward.  I think because these body header icons and text are derived from the content that is loading, they should also show loading state.

2021-10-26 15:00 UTC, ramfox approved these changes
A few nitpicks, but this looks great!

2021-10-26 15:00 UTC, ramfox commented on src/features/dataset/state/datasetState.ts
> +    state.bodyLoading = false
need to also track `API_BODY_FAILURE`, and set the `bodyLoading` to false

2021-10-26 15:00 UTC, ramfox commented on src/features/dsComponents/body/Body.tsx
> +
extra line here

2021-10-26 15:00 UTC, ramfox commented on src/features/dsComponents/body/Body.tsx
> +import {selectIsBodyLoading} from "../../dataset/state/datasetState";
```
import {selectIsBodyLoading} from "../../dataset/state/datasetState";
```
=>
```
import { selectIsBodyLoading } from "../../dataset/state/datasetState"
```

2021-10-26 15:00 UTC, ramfox commented on src/features/dsComponents/body/Body.tsx
> +import {useDispatch, useSelector} from 'react-redux'
```
import {useDispatch, useSelector} from 'react-redux'
```
=>
```
import { useDispatch, useSelector } from 'react-redux'
```

2021-10-26 15:00 UTC, ramfox commented on src/features/dsComponents/body/BodyTable.tsx
> +  loading: boolean
can we switch this to optional? Then default to `false` when you destructure it from `props`? Then we can remove `loading={false}` from the `<BodyTable>` call in `Body.tsx`

2021-10-26 15:00 UTC, ramfox commented on src/features/dsComponents/body/Body.tsx
> +        loading={false}
Can we make the `loading` param optional (defaulting to `false`), then remove this line?

2021-10-27 14:31 UTC, b5 commented on src/features/commits/CommitSummaryHeader.tsx
> +import ContentLoader from "react-content-loader";
move package imports above local imports, separated by a blank linke

2021-10-27 14:31 UTC, b5 commented on src/features/commits/CommitSummaryHeader.tsx
> +  loading: boolean
is this prop _required_? we often do loading props as optional with a default value of `false` within the component itself

2021-10-27 14:31 UTC, b5 commented on src/features/commits/CommitSummaryHeader.tsx
> +              < DatasetVersionInfo dataset={dataset} />
extraneous space: `< DatasetVersion...`

2021-10-27 14:31 UTC, b5 commented on src/features/commits/DatasetCommit.tsx
> +import ContentLoader from "react-content-loader";
move package imports above local imports

2021-10-27 14:31 UTC, b5 commented on src/features/commits/DatasetCommitListItem.tsx
> +  loading: boolean
make this optional, with a default value of `false`

2021-10-27 14:31 UTC, b5 commented on src/features/dataset/DatasetHeader.tsx
> +import ContentLoader from "react-content-loader";
move package import above local import

2021-10-27 14:31 UTC, b5 commented on src/features/dsComponents/body/BodyTable.tsx
>  // import { faSync } from '@fortawesome/free-solid-svg-icons'
remove these commented-out imports

2021-10-27 14:31 UTC, b5 commented on src/features/dsComponents/body/Body.tsx
> +    />
make `headers` and `body` BodyTable props optional, use an empty array as default values. use `loading` prop literal instead:

```ts
if (loading) {
  return <BodyTable loading />
}
```

2021-10-27 14:31 UTC, b5 commented on src/features/dsComponents/DatasetComponents.tsx
> +    }
This solution works for now, but isn't optimal. Body loading state should be handled entirely within the `loadDataset` action, and a selector like `selectBodyIsLoading` should be able to work out it's state entirely from the request lifecycle of `loadDataset`.

That said, this solution will work for now, so let's merge it. Can you file an issue titled `Revisit Body Loading State on Dataset Components page` and quote my above comment?

2021-10-29 13:28 UTC, b5 approved these changes
LGTM

2021-10-29 15:00 UTC, merged