feat: On Run log, run now button now adds an event to the table
qri-io/frontend pull request #454
Opened 2021-10-21 14:03 UTC by boandriy

On Run log, run now button now adds an event to the table with status running. Added icon next to status in run log table.

closes #418

2021-10-21 16:40 UTC, chriswhong requested changes
This looks great when status === 'running' lasts a few seconds.  However, when testing it with a run that happens quickly, the classnames update so fast that the animation is lost.  I don't know what technique we can use make the classnames persist through the running state, but I think it's worth another look.  

Here is some code that will run almost instantly you can test on:

```
load("time.star", "time")
load("dataframe.star", "dataframe")

# append the current time
current_time = time.now()

# get the previous version of this dataset
workingDataset = dataset.latest()

the_list = list(workingDataset.body['time'])
the_list = sorted(the_list + [str(current_time)], reverse=True)
print(the_list)

workingDataset.body = the_list



# finally, commit the changes
# the last step of every transform is always `dataset.commit(Dataset)`
dataset.commit(workingDataset)
```

2021-10-22 10:01 UTC, boandriy commented
Hey, @chriswhong , pushed an update that delays a bit to make sure that animation is finished.

2021-10-22 13:01 UTC, chriswhong approved these changes
I still think the experience is a bit jumpy with a quick-running workflow, but it's ok for now.  One small point: the row height is no longer 68.  LGTM once we make the row height match.

2021-10-22 14:58 UTC, b5 reviewed
Two small nits from a technical perspective. I haven't reviewed this for functionality

2021-10-22 14:58 UTC, b5 commented on src/features/activityFeed/DatasetActivityFeed.tsx
> +      const runningLog:LogItem= {
missing space

2021-10-22 14:58 UTC, b5 commented on src/features/activityFeed/DatasetActivityFeed.tsx
> +      } as LogItem
instead of coercing to a type, either use or create a `NewLogItem` constructor function whever the `LogItem` type is defined. Even if it's exactly the same, it allows setting default values for types & keeps type coercion creep out of the codebase

2021-10-25 13:57 UTC, b5 approved these changes
Looks good!

2021-10-25 14:05 UTC, merged