fix: disabling dry run button for users that are not logged in
qri-io/frontend pull request #470
Opened 2021-10-25 10:06 UTC by boandriy

disabling dry run button for users that are not logged in

fixes #441 

@chriswhong , the button has no disabled styles, I have changed the tooltip for the button to 'Please log in before running script', Let me know if I should add the styles to disabled button.

![image](https://user-images.githubusercontent.com/22635911/138676580-9f7738bc-d36e-41b3-8a43-4f36468eb136.png)

2021-10-25 14:42 UTC, chriswhong commented
Yes, we should make sure each button `type` has a `disabled` style... you should only need to pass in the `disabled` prop.

2021-10-26 07:57 UTC, boandriy commented
@chriswhong , updated button disabled styles

2021-10-26 12:43 UTC, chriswhong requested changes
I think we need to clarify the desired behavior here. Dry run should only be an option for the dataset owner. Anonymous users or logged-in users who do not own the dataset should see the disabled dry run button.

The text in the tooltip should say "Only the dataset's owner can dry run". Later we can add "forking" or "cloning" so other users can quickly replicate and try whatever public code they find in workflows.

2021-10-26 14:01 UTC, chriswhong approved these changes
LGTM

2021-10-26 15:05 UTC, ramfox approved these changes
LGTM

2021-10-26 15:07 UTC, merged